version: '3'

networks:
  db-data-net:
    driver: bridge

services:
  mysql:
    image: my-sql:1.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql-container
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - db-data-net

  pythonapp:
    image: app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - db-data-net
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  db-data:

